<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BKOcCYService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.bKOc_cY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bKOc_cY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'staff' => ['privates', '.errored..service_locator.bKOc_cY.App\\Entity\\Staff', NULL, 'Cannot autowire service ".service_locator.bKOc_cY": it needs an instance of "App\\Entity\\Staff" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'staff' => 'App\\Entity\\Staff',
        ]);
    }
}
