<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EgmQEQGService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.EgmQEQG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EgmQEQG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservation' => ['privates', '.errored..service_locator.EgmQEQG.App\\Entity\\Reservation', NULL, 'Cannot autowire service ".service_locator.EgmQEQG": it needs an instance of "App\\Entity\\Reservation" but this type has been excluded in "config/services.yaml".'],
            'reservationRepository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'reservationService' => ['privates', 'App\\Service\\Reservation\\ReservationService', 'getReservationServiceService', true],
            'timeToCancelService' => ['privates', 'App\\Service\\SessionTimeCancel\\TimeToCancel', 'getTimeToCancelService', true],
        ], [
            'reservation' => 'App\\Entity\\Reservation',
            'reservationRepository' => 'App\\Repository\\ReservationRepository',
            'reservationService' => 'App\\Service\\Reservation\\ReservationService',
            'timeToCancelService' => 'App\\Service\\SessionTimeCancel\\TimeToCancel',
        ]);
    }
}
