<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OXGpgS0Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.OXGpgS0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OXGpgS0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'branchOfficeRepository' => ['privates', 'App\\Repository\\BranchOfficeRepository', 'getBranchOfficeRepositoryService', true],
            'disciplineRepository' => ['privates', 'App\\Repository\\DisciplineRepository', 'getDisciplineRepositoryService', true],
            'reservationService' => ['privates', 'App\\Service\\Reservation\\ReservationService', 'getReservationServiceService', true],
            'sessionRepository' => ['privates', 'App\\Repository\\SessionRepository', 'getSessionRepositoryService', true],
            'staffRepository' => ['privates', 'App\\Repository\\StaffRepository', 'getStaffRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.OXGpgS0.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.OXGpgS0": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'branchOfficeRepository' => 'App\\Repository\\BranchOfficeRepository',
            'disciplineRepository' => 'App\\Repository\\DisciplineRepository',
            'reservationService' => 'App\\Service\\Reservation\\ReservationService',
            'sessionRepository' => 'App\\Repository\\SessionRepository',
            'staffRepository' => 'App\\Repository\\StaffRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
