<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fa_VApLService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Fa.vApL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Fa.vApL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'couponService' => ['privates', 'App\\Service\\CouponService', 'getCouponServiceService', true],
            'packageRepository' => ['privates', 'App\\Repository\\PackageRepository', 'getPackageRepositoryService', true],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
        ], [
            'couponService' => 'App\\Service\\CouponService',
            'packageRepository' => 'App\\Repository\\PackageRepository',
            'translator' => '?',
        ]);
    }
}
