<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AX4WRr4Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.aX4WRr4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aX4WRr4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'branchOffice' => ['privates', '.errored..service_locator.aX4WRr4.App\\Entity\\BranchOffice', NULL, 'Cannot autowire service ".service_locator.aX4WRr4": it needs an instance of "App\\Entity\\BranchOffice" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'branchOffice' => 'App\\Entity\\BranchOffice',
            'em' => '?',
        ]);
    }
}
