<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1DmtKGService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.1_dmtKG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1_dmtKG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'conekta' => ['privates', 'App\\Service\\Conekta\\ConektaService', 'getConektaServiceService', true],
            'couponService' => ['privates', 'App\\Service\\CouponService', 'getCouponServiceService', true],
            'dispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'package' => ['privates', '.errored..service_locator.1_dmtKG.App\\Entity\\Package', NULL, 'Cannot autowire service ".service_locator.1_dmtKG": it needs an instance of "App\\Entity\\Package" but this type has been excluded in "config/services.yaml".'],
            'transactionService' => ['privates', 'App\\Service\\TransactionService', 'getTransactionServiceService', true],
        ], [
            'conekta' => 'App\\Service\\Conekta\\ConektaService',
            'couponService' => 'App\\Service\\CouponService',
            'dispatcher' => '?',
            'em' => '?',
            'package' => 'App\\Entity\\Package',
            'transactionService' => 'App\\Service\\TransactionService',
        ]);
    }
}
