<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5mUmMAcService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.5mUmMAc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5mUmMAc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'coupon' => ['privates', '.errored..service_locator.5mUmMAc.App\\Entity\\Coupon', NULL, 'Cannot autowire service ".service_locator.5mUmMAc": it needs an instance of "App\\Entity\\Coupon" but this type has been excluded in "config/services.yaml".'],
            'transactionRepository' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService', true],
        ], [
            'coupon' => 'App\\Entity\\Coupon',
            'transactionRepository' => 'App\\Repository\\TransactionRepository',
        ]);
    }
}
