<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8ghfCbService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.8ghf_cb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8ghf_cb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservation' => ['privates', '.errored..service_locator.8ghf_cb.App\\Entity\\Reservation', NULL, 'Cannot autowire service ".service_locator.8ghf_cb": it needs an instance of "App\\Entity\\Reservation" but this type has been excluded in "config/services.yaml".'],
            'user' => ['privates', '.errored..service_locator.8ghf_cb.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.8ghf_cb": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'reservation' => 'App\\Entity\\Reservation',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
