<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JBxHyE6Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.JBxHyE6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JBxHyE6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservation' => ['privates', '.errored..service_locator.JBxHyE6.App\\Entity\\Reservation', NULL, 'Cannot autowire service ".service_locator.JBxHyE6": it needs an instance of "App\\Entity\\Reservation" but this type has been excluded in "config/services.yaml".'],
            'reservationService' => ['privates', 'App\\Service\\Reservation\\ReservationService', 'getReservationServiceService', true],
            'user' => ['privates', '.errored..service_locator.JBxHyE6.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.JBxHyE6": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'reservation' => 'App\\Entity\\Reservation',
            'reservationService' => 'App\\Service\\Reservation\\ReservationService',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
