<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PKTnBvHService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.PKTnBvH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PKTnBvH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'configurationRepository' => ['privates', 'App\\Repository\\ConfigurationRepository', 'getConfigurationRepositoryService', true],
            'packageRepository' => ['privates', 'App\\Repository\\PackageRepository', 'getPackageRepositoryService', true],
        ], [
            'configurationRepository' => 'App\\Repository\\ConfigurationRepository',
            'packageRepository' => 'App\\Repository\\PackageRepository',
        ]);
    }
}
