<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UqspYAService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.uqspY_A' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uqspY_A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'editDate' => ['privates', '.errored..service_locator.uqspY_A.DateTime', NULL, 'Cannot autowire service ".service_locator.uqspY_A": it references class "DateTime" but no such service exists.'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'scheduleUtil' => ['privates', 'App\\Util\\Schedule', 'getScheduleService', true],
        ], [
            'editDate' => 'DateTime',
            'em' => '?',
            'scheduleUtil' => 'App\\Util\\Schedule',
        ]);
    }
}
