<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FwjLjknService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.FwjLjkn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FwjLjkn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'branchOfficeRepository' => ['privates', 'App\\Repository\\BranchOfficeRepository', 'getBranchOfficeRepositoryService', true],
            'exerciseRoomRepository' => ['privates', 'App\\Repository\\ExerciseRoomRepository', 'getExerciseRoomRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'schedule' => ['privates', 'App\\Util\\Schedule', 'getScheduleService', true],
            'sessionRepository' => ['privates', 'App\\Repository\\SessionRepository', 'getSessionRepositoryService', true],
            'staffRepository' => ['privates', 'App\\Repository\\StaffRepository', 'getStaffRepositoryService', true],
        ], [
            'branchOfficeRepository' => 'App\\Repository\\BranchOfficeRepository',
            'exerciseRoomRepository' => 'App\\Repository\\ExerciseRoomRepository',
            'paginator' => '?',
            'schedule' => 'App\\Util\\Schedule',
            'sessionRepository' => 'App\\Repository\\SessionRepository',
            'staffRepository' => 'App\\Repository\\StaffRepository',
        ]);
    }
}
