<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AIca2vzService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.aIca2vz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aIca2vz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'eventDispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'session' => ['privates', '.errored..service_locator.aIca2vz.App\\Entity\\Session', NULL, 'Cannot autowire service ".service_locator.aIca2vz": it needs an instance of "App\\Entity\\Session" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'eventDispatcher' => '?',
            'session' => 'App\\Entity\\Session',
        ]);
    }
}
