<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A6P1qptService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.A6P1qpt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A6P1qpt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'discipline' => ['privates', '.errored..service_locator.A6P1qpt.App\\Entity\\Discipline', NULL, 'Cannot autowire service ".service_locator.A6P1qpt": it needs an instance of "App\\Entity\\Discipline" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'discipline' => 'App\\Entity\\Discipline',
            'em' => '?',
        ]);
    }
}
