<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GwAVVAsService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.gwAVVAs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gwAVVAs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'coupon' => ['privates', '.errored..service_locator.gwAVVAs.App\\Entity\\Coupon', NULL, 'Cannot autowire service ".service_locator.gwAVVAs": it needs an instance of "App\\Entity\\Coupon" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'coupon' => 'App\\Entity\\Coupon',
            'em' => '?',
        ]);
    }
}
