<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X46PzrdService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.X46Pzrd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X46Pzrd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'session' => ['privates', '.errored..service_locator.X46Pzrd.App\\Entity\\Session', NULL, 'Cannot autowire service ".service_locator.X46Pzrd": it needs an instance of "App\\Entity\\Session" but this type has been excluded in "config/services.yaml".'],
        ], [
            'session' => 'App\\Entity\\Session',
        ]);
    }
}
