<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AGa5IZService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.AGa5I_Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AGa5I_Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'staffRepository' => ['privates', 'App\\Repository\\StaffRepository', 'getStaffRepositoryService', true],
        ], [
            'staffRepository' => 'App\\Repository\\StaffRepository',
        ]);
    }
}
