<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BSjHAA0Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.bSjHAA0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.bSjHAA0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'branchOfficeRepository' => ['privates', 'App\\Repository\\BranchOfficeRepository', 'getBranchOfficeRepositoryService', true],
            'exerciseRoomRepository' => ['privates', 'App\\Repository\\ExerciseRoomRepository', 'getExerciseRoomRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'reservationRepository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.bSjHAA0.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.bSjHAA0": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'branchOfficeRepository' => 'App\\Repository\\BranchOfficeRepository',
            'exerciseRoomRepository' => 'App\\Repository\\ExerciseRoomRepository',
            'paginator' => '?',
            'reservationRepository' => 'App\\Repository\\ReservationRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
