<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored__ServiceLocator_UqspYA_DateTimeService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.uqspY_A.DateTime' shared service.
     *
     * @return \DateTime
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.uqspY_A": it references class "DateTime" but no such service exists.');
    }
}
