<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MyqO4gDService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.myqO4gD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.myqO4gD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'waitingListRepository' => ['privates', 'App\\Repository\\WaitingListRepository', 'getWaitingListRepositoryService', true],
        ], [
            'em' => '?',
            'waitingListRepository' => 'App\\Repository\\WaitingListRepository',
        ]);
    }
}
