<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A0uko1gService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.a0uko1g' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.a0uko1g'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'configurationRepository' => ['privates', 'App\\Repository\\ConfigurationRepository', 'getConfigurationRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'uploadHandler' => ['services', 'vich_uploader.upload_handler', 'getVichUploader_UploadHandlerService', true],
        ], [
            'configurationRepository' => 'App\\Repository\\ConfigurationRepository',
            'em' => '?',
            'uploadHandler' => '?',
        ]);
    }
}
