<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAppExtensionRuntimeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Twig\Runtime\AppExtensionRuntime' shared autowired service.
     *
     * @return \App\Twig\Runtime\AppExtensionRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\Twig\\Runtime\\AppExtensionRuntime'])) {
            return $container->privates['App\\Twig\\Runtime\\AppExtensionRuntime'];
        }
        $b = ($container->privates['App\\Service\\Reservation\\ReservationService'] ?? $container->load('getReservationServiceService'));

        if (isset($container->privates['App\\Twig\\Runtime\\AppExtensionRuntime'])) {
            return $container->privates['App\\Twig\\Runtime\\AppExtensionRuntime'];
        }

        return $container->privates['App\\Twig\\Runtime\\AppExtensionRuntime'] = new \App\Twig\Runtime\AppExtensionRuntime($a, $b);
    }
}
