<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBackendBuilderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Menu\BackendBuilder' shared autowired service.
     *
     * @return \App\Menu\BackendBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\Menu\\BackendBuilder'])) {
            return $container->privates['App\\Menu\\BackendBuilder'];
        }

        return $container->privates['App\\Menu\\BackendBuilder'] = new \App\Menu\BackendBuilder(($container->services['knp_menu.factory'] ?? $container->load('getKnpMenu_FactoryService')), $a);
    }
}
