<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlameableEventSubscriberService extends App_KernelProdContainer
{
    /*
     * Gets the public 'Knp\DoctrineBehaviors\EventSubscriber\BlameableEventSubscriber' shared autowired service.
     *
     * @return \Knp\DoctrineBehaviors\EventSubscriber\BlameableEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Knp\\DoctrineBehaviors\\Provider\\UserProvider'] ?? $container->load('getUserProviderService'));

        if (isset($container->services['Knp\\DoctrineBehaviors\\EventSubscriber\\BlameableEventSubscriber'])) {
            return $container->services['Knp\\DoctrineBehaviors\\EventSubscriber\\BlameableEventSubscriber'];
        }
        $b = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['Knp\\DoctrineBehaviors\\EventSubscriber\\BlameableEventSubscriber'])) {
            return $container->services['Knp\\DoctrineBehaviors\\EventSubscriber\\BlameableEventSubscriber'];
        }

        return $container->services['Knp\\DoctrineBehaviors\\EventSubscriber\\BlameableEventSubscriber'] = new \Knp\DoctrineBehaviors\EventSubscriber\BlameableEventSubscriber($a, $b, NULL);
    }
}
