<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCouponService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.5mUmMAc.App\Entity\Coupon' shared service.
     *
     * @return \App\Entity\Coupon
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.5mUmMAc": it needs an instance of "App\\Entity\\Coupon" but this type has been excluded in "config/services.yaml".');
    }
}
