<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigExtensionRuntimeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Twig\Runtime\ConfigExtensionRuntime' shared autowired service.
     *
     * @return \App\Twig\Runtime\ConfigExtensionRuntime
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Twig\\Runtime\\ConfigExtensionRuntime'] = new \App\Twig\Runtime\ConfigExtensionRuntime(($container->privates['App\\Repository\\ConfigurationRepository'] ?? $container->load('getConfigurationRepositoryService')));
    }
}
