<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConektaServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\Conekta\ConektaService' shared autowired service.
     *
     * @return \App\Service\Conekta\ConektaService
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\Conekta\\ConektaService'])) {
            return $container->privates['App\\Service\\Conekta\\ConektaService'];
        }

        return $container->privates['App\\Service\\Conekta\\ConektaService'] = new \App\Service\Conekta\ConektaService($a, ($container->privates['App\\Repository\\ConfigurationRepository'] ?? $container->load('getConfigurationRepositoryService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
