<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCouponServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\CouponService' shared autowired service.
     *
     * @return \App\Service\CouponService
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\CouponService'])) {
            return $container->privates['App\\Service\\CouponService'];
        }

        return $container->privates['App\\Service\\CouponService'] = new \App\Service\CouponService($a, ($container->services['translator'] ?? self::getTranslatorService($container)), ($container->privates['App\\Repository\\CouponRepository'] ?? $container->load('getCouponRepositoryService')));
    }
}
