<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultSluggableRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the public 'Knp\DoctrineBehaviors\Repository\DefaultSluggableRepository' shared autowired service.
     *
     * @return \Knp\DoctrineBehaviors\Repository\DefaultSluggableRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['Knp\\DoctrineBehaviors\\Repository\\DefaultSluggableRepository'])) {
            return $container->services['Knp\\DoctrineBehaviors\\Repository\\DefaultSluggableRepository'];
        }

        return $container->services['Knp\\DoctrineBehaviors\\Repository\\DefaultSluggableRepository'] = new \Knp\DoctrineBehaviors\Repository\DefaultSluggableRepository($a);
    }
}
