<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDisciplineTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\Backend\DisciplineType' shared autowired service.
     *
     * @return \App\Form\Backend\DisciplineType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\Backend\\DisciplineType'] = new \App\Form\Backend\DisciplineType();
    }
}
