<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExerciseRoomRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\ExerciseRoomRepository' shared autowired service.
     *
     * @return \App\Repository\ExerciseRoomRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ExerciseRoomRepository'] = new \App\Repository\ExerciseRoomRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
