<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_RegistryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'form.registry' shared service.
     *
     * @return \Symfony\Component\Form\FormRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['form.registry'] = new \Symfony\Component\Form\FormRegistry([new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Form\\Backend\\BranchOfficeType' => ['privates', 'App\\Form\\Backend\\BranchOfficeType', 'getBranchOfficeTypeService', true],
            'App\\Form\\Backend\\CouponType' => ['privates', 'App\\Form\\Backend\\CouponType', 'getCouponTypeService', true],
            'App\\Form\\Backend\\DisciplineType' => ['privates', 'App\\Form\\Backend\\DisciplineType', 'getDisciplineTypeService', true],
            'App\\Form\\Backend\\ExerciseRoomType' => ['privates', 'App\\Form\\Backend\\ExerciseRoomType', 'getExerciseRoomTypeService', true],
            'App\\Form\\Backend\\InstructorProfileType' => ['privates', 'App\\Form\\Backend\\InstructorProfileType', 'getInstructorProfileTypeService', true],
            'App\\Form\\Backend\\InstructorType' => ['privates', 'App\\Form\\Backend\\InstructorType', 'getInstructorTypeService', true],
            'App\\Form\\Backend\\PackageType' => ['privates', 'App\\Form\\Backend\\PackageType', 'getPackageTypeService', true],
            'App\\Form\\Backend\\PageCreateType' => ['privates', 'App\\Form\\Backend\\PageCreateType', 'getPageCreateTypeService', true],
            'App\\Form\\Backend\\PageEditType' => ['privates', 'App\\Form\\Backend\\PageEditType', 'getPageEditTypeService', true],
            'App\\Form\\Backend\\ProfileType' => ['privates', 'App\\Form\\Backend\\ProfileType', 'getProfileTypeService', true],
            'App\\Form\\Backend\\SessionType' => ['privates', 'App\\Form\\Backend\\SessionType', 'getSessionTypeService', true],
            'App\\Form\\Backend\\StaffCreateType' => ['privates', 'App\\Form\\Backend\\StaffCreateType', 'getStaffCreateTypeService', true],
            'App\\Form\\Backend\\StaffPasswordType' => ['privates', 'App\\Form\\Backend\\StaffPasswordType', 'getStaffPasswordTypeService', true],
            'App\\Form\\Backend\\TransactionType' => ['privates', 'App\\Form\\Backend\\TransactionType', 'getTransactionTypeService', true],
            'App\\Form\\Backend\\UserType' => ['privates', 'App\\Form\\Backend\\UserType', 'getUserTypeService', true],
            'App\\Form\\ConfigurationType' => ['privates', 'App\\Form\\ConfigurationType', 'getConfigurationTypeService', true],
            'App\\Form\\ProfileFormType' => ['privates', 'App\\Form\\ProfileFormType', 'getProfileFormTypeService', true],
            'App\\Form\\RegistrationFormType' => ['privates', 'App\\Form\\RegistrationFormType', 'getRegistrationFormTypeService', true],
            'App\\Form\\ResettingFormType' => ['privates', 'App\\Form\\ResettingFormType', 'getResettingFormTypeService', true],
            'Liip\\ImagineBundle\\Form\\Type\\ImageType' => ['privates', 'liip_imagine.form.type.image', 'getLiipImagine_Form_Type_ImageService', true],
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => ['privates', 'form.type.entity', 'getForm_Type_EntityService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => ['privates', 'form.type.choice', 'getForm_Type_ChoiceService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => ['privates', 'form.type.color', 'getForm_Type_ColorService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => ['privates', 'form.type.file', 'getForm_Type_FileService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => ['privates', 'form.type.form', 'getForm_Type_FormService', true],
            'Vich\\UploaderBundle\\Form\\Type\\VichFileType' => ['services', 'vich_uploader.form.type.file', 'getVichUploader_Form_Type_FileService', true],
            'Vich\\UploaderBundle\\Form\\Type\\VichImageType' => ['services', 'vich_uploader.form.type.image', 'getVichUploader_Form_Type_ImageService', true],
        ], [
            'App\\Form\\Backend\\BranchOfficeType' => '?',
            'App\\Form\\Backend\\CouponType' => '?',
            'App\\Form\\Backend\\DisciplineType' => '?',
            'App\\Form\\Backend\\ExerciseRoomType' => '?',
            'App\\Form\\Backend\\InstructorProfileType' => '?',
            'App\\Form\\Backend\\InstructorType' => '?',
            'App\\Form\\Backend\\PackageType' => '?',
            'App\\Form\\Backend\\PageCreateType' => '?',
            'App\\Form\\Backend\\PageEditType' => '?',
            'App\\Form\\Backend\\ProfileType' => '?',
            'App\\Form\\Backend\\SessionType' => '?',
            'App\\Form\\Backend\\StaffCreateType' => '?',
            'App\\Form\\Backend\\StaffPasswordType' => '?',
            'App\\Form\\Backend\\TransactionType' => '?',
            'App\\Form\\Backend\\UserType' => '?',
            'App\\Form\\ConfigurationType' => '?',
            'App\\Form\\ProfileFormType' => '?',
            'App\\Form\\RegistrationFormType' => '?',
            'App\\Form\\ResettingFormType' => '?',
            'Liip\\ImagineBundle\\Form\\Type\\ImageType' => '?',
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => '?',
            'Vich\\UploaderBundle\\Form\\Type\\VichFileType' => '?',
            'Vich\\UploaderBundle\\Form\\Type\\VichImageType' => '?',
        ]), ['Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.form.transformation_failure_handling'] ?? $container->load('getForm_TypeExtension_Form_TransformationFailureHandlingService'));
            yield 1 => ($container->privates['form.type_extension.form.http_foundation'] ?? $container->load('getForm_TypeExtension_Form_HttpFoundationService'));
            yield 2 => ($container->privates['form.type_extension.form.validator'] ?? $container->load('getForm_TypeExtension_Form_ValidatorService'));
            yield 3 => ($container->privates['form.type_extension.upload.validator'] ?? $container->load('getForm_TypeExtension_Upload_ValidatorService'));
            yield 4 => ($container->privates['form.type_extension.csrf'] ?? $container->load('getForm_TypeExtension_CsrfService'));
            yield 5 => ($container->privates['form.type_extension.form.password_hasher'] ?? $container->load('getForm_TypeExtension_Form_PasswordHasherService'));
        }, 6), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.repeated.validator'] ??= new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension());
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.submit.validator'] ??= new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension());
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\PasswordType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.password.password_hasher'] ?? $container->load('getForm_TypeExtension_Password_PasswordHasherService'));
        }, 1)], new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_guesser.validator'] ?? $container->load('getForm_TypeGuesser_ValidatorService'));
            yield 1 => ($container->privates['form.type_guesser.doctrine'] ?? $container->load('getForm_TypeGuesser_DoctrineService'));
        }, 2))], new \Symfony\Component\Form\ResolvedFormTypeFactory());
    }
}
