<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHandlerContactServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\HandlerContactService' shared autowired service.
     *
     * @return \App\Service\HandlerContactService
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['form.factory'] ?? $container->load('getForm_FactoryService'));

        if (isset($container->privates['App\\Service\\HandlerContactService'])) {
            return $container->privates['App\\Service\\HandlerContactService'];
        }

        return $container->privates['App\\Service\\HandlerContactService'] = new \App\Service\HandlerContactService($a, ($container->services['router'] ?? self::getRouterService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['App\\Repository\\ConfigurationRepository'] ?? $container->load('getConfigurationRepositoryService')), ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')));
    }
}
