<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstructorProfileTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\Backend\InstructorProfileType' shared autowired service.
     *
     * @return \App\Form\Backend\InstructorProfileType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\Backend\\InstructorProfileType'] = new \App\Form\Backend\InstructorProfileType();
    }
}
