<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoggableEventSubscriberService extends App_KernelProdContainer
{
    /*
     * Gets the public 'Knp\DoctrineBehaviors\EventSubscriber\LoggableEventSubscriber' shared autowired service.
     *
     * @return \Knp\DoctrineBehaviors\EventSubscriber\LoggableEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Knp\\DoctrineBehaviors\\EventSubscriber\\LoggableEventSubscriber'] = new \Knp\DoctrineBehaviors\EventSubscriber\LoggableEventSubscriber(($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
