<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoginSuccessListenerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\EventListener\LoginSuccessListener' shared autowired service.
     *
     * @return \App\EventListener\LoginSuccessListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\EventListener\\LoginSuccessListener'])) {
            return $container->privates['App\\EventListener\\LoginSuccessListener'];
        }

        return $container->privates['App\\EventListener\\LoginSuccessListener'] = new \App\EventListener\LoginSuccessListener($a);
    }
}
