<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPost2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.w_4AxDf.App\Entity\Post' shared service.
     *
     * @return \App\Entity\Post
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.w_4AxDf": it needs an instance of "App\\Entity\\Post" but this type has been excluded in "config/services.yaml".');
    }
}
