<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageEditTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\Backend\PageEditType' shared autowired service.
     *
     * @return \App\Form\Backend\PageEditType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\Backend\\PageEditType'] = new \App\Form\Backend\PageEditType();
    }
}
