<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPackageController2Service extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\PackageController' shared autowired service.
     *
     * @return \App\Controller\PackageController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\PackageController'] = $instance = new \App\Controller\PackageController(($container->privates['App\\Repository\\PackageRepository'] ?? $container->load('getPackageRepositoryService')), ($container->privates['App\\Repository\\TransactionRepository'] ?? $container->load('getTransactionRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\PackageController', $container));

        return $instance;
    }
}
