<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPackage2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.Az5DpIc.App\Entity\Package' shared service.
     *
     * @return \App\Entity\Package
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Az5DpIc": it needs an instance of "App\\Entity\\Package" but this type has been excluded in "config/services.yaml".');
    }
}
