<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationCanceledListenerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\EventListener\ReservationCanceledListener' shared autowired service.
     *
     * @return \App\EventListener\ReservationCanceledListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['App\\Service\\Mailer\\ReservationMailer'] ?? $container->load('getReservationMailerService'));

        if (isset($container->privates['App\\EventListener\\ReservationCanceledListener'])) {
            return $container->privates['App\\EventListener\\ReservationCanceledListener'];
        }
        $b = ($container->privates['App\\Service\\WaitingList\\WaitingListService'] ?? $container->load('getWaitingListServiceService'));

        if (isset($container->privates['App\\EventListener\\ReservationCanceledListener'])) {
            return $container->privates['App\\EventListener\\ReservationCanceledListener'];
        }

        return $container->privates['App\\EventListener\\ReservationCanceledListener'] = new \App\EventListener\ReservationCanceledListener($a, $b);
    }
}
