<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\Reservation\ReservationService' shared autowired service.
     *
     * @return \App\Service\Reservation\ReservationService
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\Reservation\\ReservationService'])) {
            return $container->privates['App\\Service\\Reservation\\ReservationService'];
        }
        $b = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['App\\Service\\Reservation\\ReservationService'])) {
            return $container->privates['App\\Service\\Reservation\\ReservationService'];
        }

        return $container->privates['App\\Service\\Reservation\\ReservationService'] = new \App\Service\Reservation\ReservationService($a, $b, ($container->privates['App\\Service\\SessionTimeCancel\\TimeToCancel'] ?? $container->load('getTimeToCancelService')), ($container->privates['security.authorization_checker'] ?? self::getSecurity_AuthorizationCheckerService($container)), ($container->privates['App\\Repository\\TransactionRepository'] ?? $container->load('getTransactionRepositoryService')), ($container->privates['App\\Repository\\ReservationRepository'] ?? $container->load('getReservationRepositoryService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
