<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationMailerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\Mailer\ReservationMailer' shared autowired service.
     *
     * @return \App\Service\Mailer\ReservationMailer
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\Service\\Mailer\\ReservationMailer'])) {
            return $container->privates['App\\Service\\Mailer\\ReservationMailer'];
        }

        return $container->privates['App\\Service\\Mailer\\ReservationMailer'] = new \App\Service\Mailer\ReservationMailer($a, ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
