<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Backend\ReservationController' shared autowired service.
     *
     * @return \App\Controller\Backend\ReservationController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Backend\\ReservationController'] = $instance = new \App\Controller\Backend\ReservationController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Backend\\ReservationController', $container));

        return $instance;
    }
}
