<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRouteAccessVoterService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\Voter\RouteAccessVoter' shared autowired service.
     *
     * @return \App\Security\Voter\RouteAccessVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Security\\Voter\\RouteAccessVoter'] = new \App\Security\Voter\RouteAccessVoter(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
