<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionAutoClosingCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\SessionAutoClosingCommand' shared autowired service.
     *
     * @return \App\Command\SessionAutoClosingCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\SessionAutoClosingCommand'] = $instance = new \App\Command\SessionAutoClosingCommand(($container->privates['App\\Repository\\SessionRepository'] ?? $container->load('getSessionRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:session:autoclosing');
        $instance->setDescription('Cierre de las clases que ya pasaron su hora de inicio.');

        return $instance;
    }
}
