<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSluggableEventSubscriberService extends App_KernelProdContainer
{
    /*
     * Gets the public 'Knp\DoctrineBehaviors\EventSubscriber\SluggableEventSubscriber' shared autowired service.
     *
     * @return \Knp\DoctrineBehaviors\EventSubscriber\SluggableEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['Knp\\DoctrineBehaviors\\EventSubscriber\\SluggableEventSubscriber'])) {
            return $container->services['Knp\\DoctrineBehaviors\\EventSubscriber\\SluggableEventSubscriber'];
        }
        $b = ($container->services['Knp\\DoctrineBehaviors\\Repository\\DefaultSluggableRepository'] ?? $container->load('getDefaultSluggableRepositoryService'));

        if (isset($container->services['Knp\\DoctrineBehaviors\\EventSubscriber\\SluggableEventSubscriber'])) {
            return $container->services['Knp\\DoctrineBehaviors\\EventSubscriber\\SluggableEventSubscriber'];
        }

        return $container->services['Knp\\DoctrineBehaviors\\EventSubscriber\\SluggableEventSubscriber'] = new \Knp\DoctrineBehaviors\EventSubscriber\SluggableEventSubscriber($a, $b);
    }
}
