<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Authenticator_BackendService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.firewall.authenticator.backend' shared service.
     *
     * @return \Symfony\Component\Security\Http\Firewall\AuthenticatorManagerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['security.authenticator.manager.backend'] ?? $container->load('getSecurity_Authenticator_Manager_BackendService'));

        if (isset($container->privates['security.firewall.authenticator.backend'])) {
            return $container->privates['security.firewall.authenticator.backend'];
        }

        return $container->privates['security.firewall.authenticator.backend'] = new \Symfony\Component\Security\Http\Firewall\AuthenticatorManagerListener($a);
    }
}
