<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\Backend\SessionType' shared autowired service.
     *
     * @return \App\Form\Backend\SessionType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Form\\Backend\\SessionType'])) {
            return $container->privates['App\\Form\\Backend\\SessionType'];
        }

        return $container->privates['App\\Form\\Backend\\SessionType'] = new \App\Form\Backend\SessionType(($container->privates['App\\Util\\Schedule'] ??= new \App\Util\Schedule()), $a);
    }
}
