<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStaffCreateCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\StaffCreateCommand' shared autowired service.
     *
     * @return \App\Command\StaffCreateCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\StaffCreateCommand'] = $instance = new \App\Command\StaffCreateCommand(($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:staff:create');
        $instance->setDescription('Staff create');

        return $instance;
    }
}
