<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScheduleService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Util\Schedule' shared autowired service.
     *
     * @return \App\Util\Schedule
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Util\\Schedule'] = new \App\Util\Schedule();
    }
}
