<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStaffProfileRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\StaffProfileRepository' shared autowired service.
     *
     * @return \App\Repository\StaffProfileRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\StaffProfileRepository'] = new \App\Repository\StaffProfileRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
