<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStaffRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\StaffRepository' shared autowired service.
     *
     * @return \App\Repository\StaffRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\StaffRepository'] = new \App\Repository\StaffRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
