<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authenticator_Manager_BackendService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.authenticator.manager.backend' shared service.
     *
     * @return \Symfony\Component\Security\Http\Authentication\AuthenticatorManager
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['security.authenticator.form_login.backend'] ?? $container->load('getSecurity_Authenticator_FormLogin_BackendService'));

        if (isset($container->privates['security.authenticator.manager.backend'])) {
            return $container->privates['security.authenticator.manager.backend'];
        }

        return $container->privates['security.authenticator.manager.backend'] = new \Symfony\Component\Security\Http\Authentication\AuthenticatorManager([$a, ($container->privates['security.authenticator.remember_me.backend'] ?? $container->load('getSecurity_Authenticator_RememberMe_BackendService'))], ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), ($container->privates['security.event_dispatcher.backend'] ?? self::getSecurity_EventDispatcher_BackendService($container)), 'backend', ($container->privates['monolog.logger.security'] ?? self::getMonolog_Logger_SecurityService($container)), true, true, []);
    }
}
