<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSoftDeletableEventSubscriberService extends App_KernelProdContainer
{
    /*
     * Gets the public 'Knp\DoctrineBehaviors\EventSubscriber\SoftDeletableEventSubscriber' shared autowired service.
     *
     * @return \Knp\DoctrineBehaviors\EventSubscriber\SoftDeletableEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Knp\\DoctrineBehaviors\\EventSubscriber\\SoftDeletableEventSubscriber'] = new \Knp\DoctrineBehaviors\EventSubscriber\SoftDeletableEventSubscriber();
    }
}
