<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStaffService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.AU_1vwh.App\Entity\Staff' shared service.
     *
     * @return \App\Entity\Staff
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.AU_1vwh": it needs an instance of "App\\Entity\\Staff" but this type has been excluded in "config/services.yaml".');
    }
}
