<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStaffCreateCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\StaffCreateCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\StaffCreateCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:staff:create', [], 'Staff create', false, #[\Closure(name: 'App\\Command\\StaffCreateCommand')] fn (): \App\Command\StaffCreateCommand => ($container->privates['App\\Command\\StaffCreateCommand'] ?? $container->load('getStaffCreateCommandService')));
    }
}
