<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatsControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Backend\StatsController' shared autowired service.
     *
     * @return \App\Controller\Backend\StatsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\Backend\\StatsController'] = $instance = new \App\Controller\Backend\StatsController(($container->privates['App\\Repository\\TransactionRepository'] ?? $container->load('getTransactionRepositoryService')), ($container->privates['App\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')), ($container->privates['App\\Repository\\ReservationRepository'] ?? $container->load('getReservationRepositoryService')), ($container->privates['App\\Repository\\ConfigurationRepository'] ?? $container->load('getConfigurationRepositoryService')), ($container->privates['App\\Repository\\ExerciseRoomRepository'] ?? $container->load('getExerciseRoomRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\Backend\\StatsController', $container));

        return $instance;
    }
}
