<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionAutoClosingCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\SessionAutoClosingCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\SessionAutoClosingCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:session:autoclosing', [], 'Cierre de las clases que ya pasaron su hora de inicio.', false, #[\Closure(name: 'App\\Command\\SessionAutoClosingCommand')] fn (): \App\Command\SessionAutoClosingCommand => ($container->privates['App\\Command\\SessionAutoClosingCommand'] ?? $container->load('getSessionAutoClosingCommandService')));
    }
}
