<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransactionServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\TransactionService' shared autowired service.
     *
     * @return \App\Service\TransactionService
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\Service\\TransactionService'])) {
            return $container->privates['App\\Service\\TransactionService'];
        }

        return $container->privates['App\\Service\\TransactionService'] = new \App\Service\TransactionService($a);
    }
}
