<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTranslatableEventSubscriberService extends App_KernelProdContainer
{
    /*
     * Gets the public 'Knp\DoctrineBehaviors\EventSubscriber\TranslatableEventSubscriber' shared autowired service.
     *
     * @return \Knp\DoctrineBehaviors\EventSubscriber\TranslatableEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Knp\\DoctrineBehaviors\\EventSubscriber\\TranslatableEventSubscriber'] = new \Knp\DoctrineBehaviors\EventSubscriber\TranslatableEventSubscriber(($container->services['Knp\\DoctrineBehaviors\\Provider\\LocaleProvider'] ?? $container->load('getLocaleProviderService')), 'LAZY', 'LAZY');
    }
}
