<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransactionCheckExpirationCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\TransactionCheckExpirationCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\TransactionCheckExpirationCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:transaction:checkexpiration', [], 'Cierre de las transacciones que ya expirarón.', false, #[\Closure(name: 'App\\Command\\TransactionCheckExpirationCommand')] fn (): \App\Command\TransactionCheckExpirationCommand => ($container->privates['App\\Command\\TransactionCheckExpirationCommand'] ?? $container->load('getTransactionCheckExpirationCommandService')));
    }
}
