<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransactionSuccessListenerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\EventListener\TransactionSuccessListener' shared autowired service.
     *
     * @return \App\EventListener\TransactionSuccessListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['App\\Service\\CouponService'] ?? $container->load('getCouponServiceService'));

        if (isset($container->privates['App\\EventListener\\TransactionSuccessListener'])) {
            return $container->privates['App\\EventListener\\TransactionSuccessListener'];
        }

        return $container->privates['App\\EventListener\\TransactionSuccessListener'] = new \App\EventListener\TransactionSuccessListener(($container->privates['App\\Service\\Mailer\\TransactionMailer'] ?? $container->load('getTransactionMailerService')), $a);
    }
}
