<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransactionCheckExpirationCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\TransactionCheckExpirationCommand' shared autowired service.
     *
     * @return \App\Command\TransactionCheckExpirationCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\TransactionCheckExpirationCommand'] = $instance = new \App\Command\TransactionCheckExpirationCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\TransactionRepository'] ?? $container->load('getTransactionRepositoryService')), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)));

        $instance->setName('app:transaction:checkexpiration');
        $instance->setDescription('Cierre de las transacciones que ya expirarón.');

        return $instance;
    }
}
