<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimeToCancelService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\SessionTimeCancel\TimeToCancel' shared autowired service.
     *
     * @return \App\Service\SessionTimeCancel\TimeToCancel
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\SessionTimeCancel\\TimeToCancel'] = new \App\Service\SessionTimeCancel\TimeToCancel(($container->privates['App\\Repository\\ConfigurationRepository'] ?? $container->load('getConfigurationRepositoryService')));
    }
}
