<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransactionExpiredListenerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\EventListener\TransactionExpiredListener' shared autowired service.
     *
     * @return \App\EventListener\TransactionExpiredListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['App\\Service\\Mailer\\TransactionMailer'] ?? $container->load('getTransactionMailerService'));

        if (isset($container->privates['App\\EventListener\\TransactionExpiredListener'])) {
            return $container->privates['App\\EventListener\\TransactionExpiredListener'];
        }

        return $container->privates['App\\EventListener\\TransactionExpiredListener'] = new \App\EventListener\TransactionExpiredListener($a);
    }
}
