<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserProviderService extends App_KernelProdContainer
{
    /*
     * Gets the public 'Knp\DoctrineBehaviors\Provider\UserProvider' shared autowired service.
     *
     * @return \Knp\DoctrineBehaviors\Provider\UserProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->services['Knp\\DoctrineBehaviors\\Provider\\UserProvider'])) {
            return $container->services['Knp\\DoctrineBehaviors\\Provider\\UserProvider'];
        }

        return $container->services['Knp\\DoctrineBehaviors\\Provider\\UserProvider'] = new \Knp\DoctrineBehaviors\Provider\UserProvider($a, NULL);
    }
}
