<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserMailerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\Mailer\UserMailer' shared autowired service.
     *
     * @return \App\Service\Mailer\UserMailer
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\Mailer\\UserMailer'] = new \App\Service\Mailer\UserMailer(($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService')));
    }
}
