<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWaitingListSuccessListenerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\EventListener\WaitingListSuccessListener' shared autowired service.
     *
     * @return \App\EventListener\WaitingListSuccessListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\EventListener\\WaitingListSuccessListener'])) {
            return $container->privates['App\\EventListener\\WaitingListSuccessListener'];
        }

        return $container->privates['App\\EventListener\\WaitingListSuccessListener'] = new \App\EventListener\WaitingListSuccessListener(new \App\Service\Mailer\WaitingListMailer($a, ($container->privates['monolog.logger'] ?? $container->load('getMonolog_LoggerService'))));
    }
}
