<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWaitingListExpireCommandService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Command\WaitingListExpireCommand' shared autowired service.
     *
     * @return \App\Command\WaitingListExpireCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\WaitingListExpireCommand'] = $instance = new \App\Command\WaitingListExpireCommand(($container->privates['App\\Repository\\WaitingListRepository'] ?? $container->load('getWaitingListRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:waiting-list:expire');
        $instance->setDescription('Expirar lista de espera');

        return $instance;
    }
}
