<?php

namespace ContainerCkDdc8D;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWaitingListExpireCommand_LazyService extends App_KernelProdContainer
{
    /*
     * Gets the private '.App\Command\WaitingListExpireCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\WaitingListExpireCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:waiting-list:expire', [], 'Expirar lista de espera', false, #[\Closure(name: 'App\\Command\\WaitingListExpireCommand')] fn (): \App\Command\WaitingListExpireCommand => ($container->privates['App\\Command\\WaitingListExpireCommand'] ?? $container->load('getWaitingListExpireCommandService')));
    }
}
