<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCkDdc8D\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCkDdc8D/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerCkDdc8D.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerCkDdc8D\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerCkDdc8D\App_KernelProdContainer([
    'container.build_hash' => 'CkDdc8D',
    'container.build_id' => '097e5836',
    'container.build_time' => 1738203171,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCkDdc8D');
