<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ALT7L0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.a_LT7L0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.a_LT7L0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'conekta' => ['privates', 'App\\Service\\Conekta\\ConektaService', 'getConektaServiceService', true],
            'couponService' => ['privates', 'App\\Service\\CouponService', 'getCouponServiceService', true],
            'dispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'transactionService' => ['privates', 'App\\Service\\TransactionService', 'getTransactionServiceService', true],
        ], [
            'conekta' => 'App\\Service\\Conekta\\ConektaService',
            'couponService' => 'App\\Service\\CouponService',
            'dispatcher' => '?',
            'em' => '?',
            'transactionService' => 'App\\Service\\TransactionService',
        ]);
    }
}
