<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9oqSKZKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9oqSKZK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9oqSKZK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contactService' => ['privates', 'App\\Service\\HandlerContactService', 'getHandlerContactServiceService', true],
        ], [
            'contactService' => 'App\\Service\\HandlerContactService',
        ]);
    }
}
