<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fu5S5zSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Fu5S5zS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Fu5S5zS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'exerciseRoomRepository' => ['privates', 'App\\Repository\\ExerciseRoomRepository', 'getExerciseRoomRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'exerciseRoomRepository' => 'App\\Repository\\ExerciseRoomRepository',
            'paginator' => '?',
        ]);
    }
}
