<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RkGgYmeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RkGgYme' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RkGgYme'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservationRepository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'reservationService' => ['privates', 'App\\Service\\Reservation\\ReservationService', 'getReservationServiceService', true],
            'session' => ['privates', '.errored..service_locator.RkGgYme.App\\Entity\\Session', NULL, 'Cannot autowire service ".service_locator.RkGgYme": it needs an instance of "App\\Entity\\Session" but this type has been excluded in "config/services.yaml".'],
            'waitingListService' => ['privates', 'App\\Service\\WaitingList\\WaitingListService', 'getWaitingListServiceService', true],
        ], [
            'reservationRepository' => 'App\\Repository\\ReservationRepository',
            'reservationService' => 'App\\Service\\Reservation\\ReservationService',
            'session' => 'App\\Entity\\Session',
            'waitingListService' => 'App\\Service\\WaitingList\\WaitingListService',
        ]);
    }
}
