<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T3Fa3CQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t3Fa3CQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t3Fa3CQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'transaction' => ['privates', '.errored..service_locator.t3Fa3CQ.App\\Entity\\Transaction', NULL, 'Cannot autowire service ".service_locator.t3Fa3CQ": it needs an instance of "App\\Entity\\Transaction" but this type has been excluded in "config/services.yaml".'],
        ], [
            'transaction' => 'App\\Entity\\Transaction',
        ]);
    }
}
