<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2RjsZqSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2RjsZqS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2RjsZqS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'branchOfficeRepository' => ['privates', 'App\\Repository\\BranchOfficeRepository', 'getBranchOfficeRepositoryService', true],
            'packageRepository' => ['privates', 'App\\Repository\\PackageRepository', 'getPackageRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'transactionRepository' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService', true],
        ], [
            'branchOfficeRepository' => 'App\\Repository\\BranchOfficeRepository',
            'packageRepository' => 'App\\Repository\\PackageRepository',
            'paginator' => '?',
            'transactionRepository' => 'App\\Repository\\TransactionRepository',
        ]);
    }
}
