<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RXGVxLFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RXGVxLF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RXGVxLF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'transactionRepository' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.RXGVxLF.App\\Entity\\User', NULL, 'Cannot autowire service ".service_locator.RXGVxLF": it needs an instance of "App\\Entity\\User" but this type has been excluded in "config/services.yaml".'],
        ], [
            'paginator' => '?',
            'transactionRepository' => 'App\\Repository\\TransactionRepository',
            'user' => 'App\\Entity\\User',
        ]);
    }
}
