<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LteH55BService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LteH55B' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LteH55B'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'exerciseRoom' => ['privates', '.errored..service_locator.LteH55B.App\\Entity\\ExerciseRoom', NULL, 'Cannot autowire service ".service_locator.LteH55B": it needs an instance of "App\\Entity\\ExerciseRoom" but this type has been excluded in "config/services.yaml".'],
            'sessionRepository' => ['privates', 'App\\Repository\\SessionRepository', 'getSessionRepositoryService', true],
        ], [
            'em' => '?',
            'exerciseRoom' => 'App\\Entity\\ExerciseRoom',
            'sessionRepository' => 'App\\Repository\\SessionRepository',
        ]);
    }
}
