<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BOoxCP4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BOoxCP4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BOoxCP4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'session' => ['privates', '.errored..service_locator.BOoxCP4.App\\Entity\\Session', NULL, 'Cannot autowire service ".service_locator.BOoxCP4": it needs an instance of "App\\Entity\\Session" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'session' => 'App\\Entity\\Session',
        ]);
    }
}
