<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6R59VweService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6R59Vwe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6R59Vwe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'branchOfficeRepository' => ['privates', 'App\\Repository\\BranchOfficeRepository', 'getBranchOfficeRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'exerciseRoomRepository' => ['privates', 'App\\Repository\\ExerciseRoomRepository', 'getExerciseRoomRepositoryService', true],
            'instructorRepository' => ['privates', 'App\\Repository\\StaffRepository', 'getStaffRepositoryService', true],
            'scheduleUtil' => ['privates', 'App\\Util\\Schedule', 'getScheduleService', true],
        ], [
            'branchOfficeRepository' => 'App\\Repository\\BranchOfficeRepository',
            'em' => '?',
            'exerciseRoomRepository' => 'App\\Repository\\ExerciseRoomRepository',
            'instructorRepository' => 'App\\Repository\\StaffRepository',
            'scheduleUtil' => 'App\\Util\\Schedule',
        ]);
    }
}
