<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NReehSTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NReehST' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NReehST'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'conektaService' => ['privates', 'App\\Service\\Conekta\\ConektaService', 'getConektaServiceService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'transaction' => ['privates', '.errored..service_locator.NReehST.App\\Entity\\Transaction', NULL, 'Cannot autowire service ".service_locator.NReehST": it needs an instance of "App\\Entity\\Transaction" but this type has been excluded in "config/services.yaml".'],
        ], [
            'conektaService' => 'App\\Service\\Conekta\\ConektaService',
            'em' => '?',
            'transaction' => 'App\\Entity\\Transaction',
        ]);
    }
}
