<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DvFBom3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DvFBom3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DvFBom3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'session' => ['privates', '.errored..service_locator.DvFBom3.App\\Entity\\Session', NULL, 'Cannot autowire service ".service_locator.DvFBom3": it needs an instance of "App\\Entity\\Session" but this type has been excluded in "config/services.yaml".'],
            'waitingListService' => ['privates', 'App\\Service\\WaitingList\\WaitingListService', 'getWaitingListServiceService', true],
        ], [
            'session' => 'App\\Entity\\Session',
            'waitingListService' => 'App\\Service\\WaitingList\\WaitingListService',
        ]);
    }
}
