<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G1tuWenService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G1tuWen' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G1tuWen'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sessionRepository' => ['privates', 'App\\Repository\\SessionRepository', 'getSessionRepositoryService', true],
            'sessionTimeToCancel' => ['privates', 'App\\Service\\SessionTimeCancel\\TimeToCancel', 'getTimeToCancelService', true],
        ], [
            'sessionRepository' => 'App\\Repository\\SessionRepository',
            'sessionTimeToCancel' => 'App\\Service\\SessionTimeCancel\\TimeToCancel',
        ]);
    }
}
