<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EvwCW2BService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.evwCW2B' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.evwCW2B'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'branchOfficeRepository' => ['privates', 'App\\Repository\\BranchOfficeRepository', 'getBranchOfficeRepositoryService', true],
            'disciplineRepository' => ['privates', 'App\\Repository\\DisciplineRepository', 'getDisciplineRepositoryService', true],
            'sessionRepository' => ['privates', 'App\\Repository\\SessionRepository', 'getSessionRepositoryService', true],
            'staffRepository' => ['privates', 'App\\Repository\\StaffRepository', 'getStaffRepositoryService', true],
        ], [
            'branchOfficeRepository' => 'App\\Repository\\BranchOfficeRepository',
            'disciplineRepository' => 'App\\Repository\\DisciplineRepository',
            'sessionRepository' => 'App\\Repository\\SessionRepository',
            'staffRepository' => 'App\\Repository\\StaffRepository',
        ]);
    }
}
