<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Az5DpIcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Az5DpIc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Az5DpIc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'couponService' => ['privates', 'App\\Service\\CouponService', 'getCouponServiceService', true],
            'package' => ['privates', '.errored..service_locator.Az5DpIc.App\\Entity\\Package', NULL, 'Cannot autowire service ".service_locator.Az5DpIc": it needs an instance of "App\\Entity\\Package" but this type has been excluded in "config/services.yaml".'],
            'translator' => ['services', 'translator', 'getTranslatorService', false],
        ], [
            'couponService' => 'App\\Service\\CouponService',
            'package' => 'App\\Entity\\Package',
            'translator' => '?',
        ]);
    }
}
