<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Pi2gBgzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pi2gBgz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pi2gBgz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'package' => ['privates', '.errored..service_locator.pi2gBgz.App\\Entity\\Package', NULL, 'Cannot autowire service ".service_locator.pi2gBgz": it needs an instance of "App\\Entity\\Package" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'package' => 'App\\Entity\\Package',
        ]);
    }
}
