<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlameableEventSubscriberService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Knp\DoctrineBehaviors\EventSubscriber\BlameableEventSubscriber' shared autowired service.
     *
     * @return \Knp\DoctrineBehaviors\EventSubscriber\BlameableEventSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'doctrine'.\DIRECTORY_SEPARATOR.'event-manager'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'doctrine'.\DIRECTORY_SEPARATOR.'doctrine-bundle'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'EventSubscriberInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'knplabs'.\DIRECTORY_SEPARATOR.'doctrine-behaviors'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventSubscriber'.\DIRECTORY_SEPARATOR.'BlameableEventSubscriber.php';

        $a = ($container->services['Knp\\DoctrineBehaviors\\Provider\\UserProvider'] ?? $container->load('getUserProviderService'));

        if (isset($container->services['Knp\\DoctrineBehaviors\\EventSubscriber\\BlameableEventSubscriber'])) {
            return $container->services['Knp\\DoctrineBehaviors\\EventSubscriber\\BlameableEventSubscriber'];
        }
        $b = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['Knp\\DoctrineBehaviors\\EventSubscriber\\BlameableEventSubscriber'])) {
            return $container->services['Knp\\DoctrineBehaviors\\EventSubscriber\\BlameableEventSubscriber'];
        }

        return $container->services['Knp\\DoctrineBehaviors\\EventSubscriber\\BlameableEventSubscriber'] = new \Knp\DoctrineBehaviors\EventSubscriber\BlameableEventSubscriber($a, $b, NULL);
    }
}
