<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBranchOfficeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.aX4WRr4.App\Entity\BranchOffice' shared service.
     *
     * @return \App\Entity\BranchOffice
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.aX4WRr4": it needs an instance of "App\\Entity\\BranchOffice" but this type has been excluded in "config/services.yaml".');
    }
}
