<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConektaServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Conekta\ConektaService' shared autowired service.
     *
     * @return \App\Service\Conekta\ConektaService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'conekta'.\DIRECTORY_SEPARATOR.'conekta-php'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'Conekta'.\DIRECTORY_SEPARATOR.'Conekta.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Conekta'.\DIRECTORY_SEPARATOR.'ConektaBase.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Conekta'.\DIRECTORY_SEPARATOR.'ConektaService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\Conekta\\ConektaService'])) {
            return $container->privates['App\\Service\\Conekta\\ConektaService'];
        }

        return $container->privates['App\\Service\\Conekta\\ConektaService'] = new \App\Service\Conekta\ConektaService($a, ($container->privates['App\\Repository\\ConfigurationRepository'] ?? $container->load('getConfigurationRepositoryService')), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
