<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDisciplineService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.A6P1qpt.App\Entity\Discipline' shared service.
     *
     * @return \App\Entity\Discipline
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.A6P1qpt": it needs an instance of "App\\Entity\\Discipline" but this type has been excluded in "config/services.yaml".');
    }
}
