<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultSluggableRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Knp\DoctrineBehaviors\Repository\DefaultSluggableRepository' shared autowired service.
     *
     * @return \Knp\DoctrineBehaviors\Repository\DefaultSluggableRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'knplabs'.\DIRECTORY_SEPARATOR.'doctrine-behaviors'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Repository'.\DIRECTORY_SEPARATOR.'DefaultSluggableRepository.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['Knp\\DoctrineBehaviors\\Repository\\DefaultSluggableRepository'])) {
            return $container->services['Knp\\DoctrineBehaviors\\Repository\\DefaultSluggableRepository'];
        }

        return $container->services['Knp\\DoctrineBehaviors\\Repository\\DefaultSluggableRepository'] = new \Knp\DoctrineBehaviors\Repository\DefaultSluggableRepository($a);
    }
}
