<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLocaleProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Knp\DoctrineBehaviors\Provider\LocaleProvider' shared autowired service.
     *
     * @return \Knp\DoctrineBehaviors\Provider\LocaleProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'knplabs'.\DIRECTORY_SEPARATOR.'doctrine-behaviors'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Contract'.\DIRECTORY_SEPARATOR.'Provider'.\DIRECTORY_SEPARATOR.'LocaleProviderInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'knplabs'.\DIRECTORY_SEPARATOR.'doctrine-behaviors'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Provider'.\DIRECTORY_SEPARATOR.'LocaleProvider.php';

        return $container->services['Knp\\DoctrineBehaviors\\Provider\\LocaleProvider'] = new \Knp\DoctrineBehaviors\Provider\LocaleProvider(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)), ($container->services['translator'] ?? self::getTranslatorService($container)));
    }
}
