<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationSuccessListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\ReservationSuccessListener' shared autowired service.
     *
     * @return \App\EventListener\ReservationSuccessListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'ReservationSuccessListener.php';

        $a = ($container->privates['App\\Service\\Mailer\\ReservationMailer'] ?? $container->load('getReservationMailerService'));

        if (isset($container->privates['App\\EventListener\\ReservationSuccessListener'])) {
            return $container->privates['App\\EventListener\\ReservationSuccessListener'];
        }

        return $container->privates['App\\EventListener\\ReservationSuccessListener'] = new \App\EventListener\ReservationSuccessListener($a);
    }
}
