<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getResettingMailerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\Mailer\ResettingMailer' shared autowired service.
     *
     * @return \App\Service\Mailer\ResettingMailer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Mailer'.\DIRECTORY_SEPARATOR.'AbstractMailManager.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Mailer'.\DIRECTORY_SEPARATOR.'ResettingMailer.php';

        return $container->privates['App\\Service\\Mailer\\ResettingMailer'] = new \App\Service\Mailer\ResettingMailer(($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService')), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ($container->services['router'] ?? self::getRouterService($container)));
    }
}
