<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservation5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.jz1DUg2.App\Entity\Reservation' shared service.
     *
     * @return \App\Entity\Reservation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.jz1DUg2": it needs an instance of "App\\Entity\\Reservation" but this type has been excluded in "config/services.yaml".');
    }
}
