<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSessionAutoClosingCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\SessionAutoClosingCommand' shared autowired service.
     *
     * @return \App\Command\SessionAutoClosingCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'AbstractCommand.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'SessionAutoClosingCommand.php';

        $container->privates['App\\Command\\SessionAutoClosingCommand'] = $instance = new \App\Command\SessionAutoClosingCommand(($container->privates['App\\Repository\\SessionRepository'] ?? $container->load('getSessionRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:session:autoclosing');
        $instance->setDescription('Cierre de las clases que ya pasaron su hora de inicio.');

        return $instance;
    }
}
