<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStaff3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.rbVztll.App\Entity\Staff' shared service.
     *
     * @return \App\Entity\Staff
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.rbVztll": it needs an instance of "App\\Entity\\Staff" but this type has been excluded in "config/services.yaml".');
    }
}
