<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScheduleService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Util\Schedule' shared autowired service.
     *
     * @return \App\Util\Schedule
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Util'.\DIRECTORY_SEPARATOR.'Schedule.php';

        return $container->privates['App\\Util\\Schedule'] = new \App\Util\Schedule();
    }
}
