<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSession4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.X46Pzrd.App\Entity\Session' shared service.
     *
     * @return \App\Entity\Session
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.X46Pzrd": it needs an instance of "App\\Entity\\Session" but this type has been excluded in "config/services.yaml".');
    }
}
