<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransactionCheckExpirationCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\TransactionCheckExpirationCommand' shared autowired service.
     *
     * @return \App\Command\TransactionCheckExpirationCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'AbstractCommand.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'TransactionCheckExpirationCommand.php';

        $container->privates['App\\Command\\TransactionCheckExpirationCommand'] = $instance = new \App\Command\TransactionCheckExpirationCommand(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['App\\Repository\\TransactionRepository'] ?? $container->load('getTransactionRepositoryService')), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)));

        $instance->setName('app:transaction:checkexpiration');
        $instance->setDescription('Cierre de las transacciones que ya expirarón.');

        return $instance;
    }
}
