<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransactionSuccessListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\TransactionSuccessListener' shared autowired service.
     *
     * @return \App\EventListener\TransactionSuccessListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'TransactionSuccessListener.php';

        $a = ($container->privates['App\\Service\\CouponService'] ?? $container->load('getCouponServiceService'));

        if (isset($container->privates['App\\EventListener\\TransactionSuccessListener'])) {
            return $container->privates['App\\EventListener\\TransactionSuccessListener'];
        }

        return $container->privates['App\\EventListener\\TransactionSuccessListener'] = new \App\EventListener\TransactionSuccessListener(($container->privates['App\\Service\\Mailer\\TransactionMailer'] ?? $container->load('getTransactionMailerService')), $a);
    }
}
