<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransaction3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.t3Fa3CQ.App\Entity\Transaction' shared service.
     *
     * @return \App\Entity\Transaction
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.t3Fa3CQ": it needs an instance of "App\\Entity\\Transaction" but this type has been excluded in "config/services.yaml".');
    }
}
