<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimeToCancelService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SessionTimeCancel\TimeToCancel' shared autowired service.
     *
     * @return \App\Service\SessionTimeCancel\TimeToCancel
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'SessionTimeCancel'.\DIRECTORY_SEPARATOR.'TimeToCancel.php';

        return $container->privates['App\\Service\\SessionTimeCancel\\TimeToCancel'] = new \App\Service\SessionTimeCancel\TimeToCancel(($container->privates['App\\Repository\\ConfigurationRepository'] ?? $container->load('getConfigurationRepositoryService')));
    }
}
