<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTransactionExpiredListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\TransactionExpiredListener' shared autowired service.
     *
     * @return \App\EventListener\TransactionExpiredListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'TransactionExpiredListener.php';

        $a = ($container->privates['App\\Service\\Mailer\\TransactionMailer'] ?? $container->load('getTransactionMailerService'));

        if (isset($container->privates['App\\EventListener\\TransactionExpiredListener'])) {
            return $container->privates['App\\EventListener\\TransactionExpiredListener'];
        }

        return $container->privates['App\\EventListener\\TransactionExpiredListener'] = new \App\EventListener\TransactionExpiredListener($a);
    }
}
