<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'Knp\DoctrineBehaviors\Provider\UserProvider' shared autowired service.
     *
     * @return \Knp\DoctrineBehaviors\Provider\UserProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'knplabs'.\DIRECTORY_SEPARATOR.'doctrine-behaviors'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Contract'.\DIRECTORY_SEPARATOR.'Provider'.\DIRECTORY_SEPARATOR.'UserProviderInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'knplabs'.\DIRECTORY_SEPARATOR.'doctrine-behaviors'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Provider'.\DIRECTORY_SEPARATOR.'UserProvider.php';

        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->services['Knp\\DoctrineBehaviors\\Provider\\UserProvider'])) {
            return $container->services['Knp\\DoctrineBehaviors\\Provider\\UserProvider'];
        }

        return $container->services['Knp\\DoctrineBehaviors\\Provider\\UserProvider'] = new \Knp\DoctrineBehaviors\Provider\UserProvider($a, NULL);
    }
}
