<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWaitingListServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\WaitingList\WaitingListService' shared autowired service.
     *
     * @return \App\Service\WaitingList\WaitingListService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'WaitingList'.\DIRECTORY_SEPARATOR.'WaitingListService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\WaitingList\\WaitingListService'])) {
            return $container->privates['App\\Service\\WaitingList\\WaitingListService'];
        }
        $b = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->privates['App\\Service\\WaitingList\\WaitingListService'])) {
            return $container->privates['App\\Service\\WaitingList\\WaitingListService'];
        }
        $c = ($container->privates['App\\Service\\Reservation\\ReservationService'] ?? $container->load('getReservationServiceService'));

        if (isset($container->privates['App\\Service\\WaitingList\\WaitingListService'])) {
            return $container->privates['App\\Service\\WaitingList\\WaitingListService'];
        }

        return $container->privates['App\\Service\\WaitingList\\WaitingListService'] = new \App\Service\WaitingList\WaitingListService($a, $b, ($container->privates['App\\Service\\SessionTimeCancel\\TimeToCancel'] ?? $container->load('getTimeToCancelService')), $c, ($container->privates['App\\Repository\\WaitingListRepository'] ?? $container->load('getWaitingListRepositoryService')), ($container->privates['App\\Repository\\TransactionRepository'] ?? $container->load('getTransactionRepositoryService')), ($container->privates['App\\Repository\\ReservationRepository'] ?? $container->load('getReservationRepositoryService')));
    }
}
