<?php

namespace ContainerQnPwRza;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWaitingListSuccessListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\WaitingListSuccessListener' shared autowired service.
     *
     * @return \App\EventListener\WaitingListSuccessListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'EventListener'.\DIRECTORY_SEPARATOR.'WaitingListSuccessListener.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Mailer'.\DIRECTORY_SEPARATOR.'AbstractMailManager.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'Mailer'.\DIRECTORY_SEPARATOR.'WaitingListMailer.php';

        $a = ($container->privates['mailer.mailer'] ?? $container->load('getMailer_MailerService'));

        if (isset($container->privates['App\\EventListener\\WaitingListSuccessListener'])) {
            return $container->privates['App\\EventListener\\WaitingListSuccessListener'];
        }

        return $container->privates['App\\EventListener\\WaitingListSuccessListener'] = new \App\EventListener\WaitingListSuccessListener(new \App\Service\Mailer\WaitingListMailer($a, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container))));
    }
}
