<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSJu6Nwk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSJu6Nwk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSJu6Nwk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSJu6Nwk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSJu6Nwk\App_KernelDevDebugContainer([
    'container.build_hash' => 'SJu6Nwk',
    'container.build_id' => 'a8316bf0',
    'container.build_time' => 1772752533,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSJu6Nwk');
