<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXYwnilc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXYwnilc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXYwnilc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXYwnilc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXYwnilc\App_KernelDevDebugContainer([
    'container.build_hash' => 'XYwnilc',
    'container.build_id' => 'b6c41b89',
    'container.build_time' => 1772751739,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXYwnilc');
