<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.537605f9.js',
                '/build/764.fb8851c5.js',
                '/build/3.864c1009.js',
                '/build/app.35fbe469.js',
            ],
            'css' => [
                '/build/app.3faa26e7.css',
            ],
        ],
        'backend' => [
            'js' => [
                '/build/runtime.537605f9.js',
                '/build/764.fb8851c5.js',
                '/build/800.867ac754.js',
                '/build/backend.ece7d4ff.js',
            ],
            'css' => [
                '/build/800.0b4916e2.css',
                '/build/backend.72a3f211.css',
            ],
        ],
    ],
],

]];
