<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Staff extends \App\Entity\Staff implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'branchOffices' => [parent::class, 'branchOffices', null],
        "\0".parent::class."\0".'deleted' => [parent::class, 'deleted', null],
        "\0".parent::class."\0".'disciplines' => [parent::class, 'disciplines', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null],
        "\0".parent::class."\0".'lastLogin' => [parent::class, 'lastLogin', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'permissions' => [parent::class, 'permissions', null],
        "\0".parent::class."\0".'profile' => [parent::class, 'profile', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'username' => [parent::class, 'username', null],
        'branchOffices' => [parent::class, 'branchOffices', null],
        'deleted' => [parent::class, 'deleted', null],
        'disciplines' => [parent::class, 'disciplines', null],
        'email' => [parent::class, 'email', null],
        'id' => [parent::class, 'id', null],
        'isActive' => [parent::class, 'isActive', null],
        'lastLogin' => [parent::class, 'lastLogin', null],
        'password' => [parent::class, 'password', null],
        'permissions' => [parent::class, 'permissions', null],
        'profile' => [parent::class, 'profile', null],
        'roles' => [parent::class, 'roles', null],
        'username' => [parent::class, 'username', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
