<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Coupon extends \App\Entity\Coupon implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".'*'."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        "\0".parent::class."\0".'applySpecialPrice' => [parent::class, 'applySpecialPrice', null],
        "\0".parent::class."\0".'code' => [parent::class, 'code', null],
        "\0".parent::class."\0".'couponHistories' => [parent::class, 'couponHistories', null],
        "\0".parent::class."\0".'dateEnd' => [parent::class, 'dateEnd', null],
        "\0".parent::class."\0".'dateStart' => [parent::class, 'dateStart', null],
        "\0".parent::class."\0".'discount' => [parent::class, 'discount', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'packages' => [parent::class, 'packages', null],
        "\0".parent::class."\0".'used' => [parent::class, 'used', null],
        "\0".parent::class."\0".'usesTotal' => [parent::class, 'usesTotal', null],
        'applySpecialPrice' => [parent::class, 'applySpecialPrice', null],
        'code' => [parent::class, 'code', null],
        'couponHistories' => [parent::class, 'couponHistories', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'dateEnd' => [parent::class, 'dateEnd', null],
        'dateStart' => [parent::class, 'dateStart', null],
        'discount' => [parent::class, 'discount', null],
        'id' => [parent::class, 'id', null],
        'name' => [parent::class, 'name', null],
        'packages' => [parent::class, 'packages', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
        'used' => [parent::class, 'used', null],
        'usesTotal' => [parent::class, 'usesTotal', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
