<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class BranchOffice extends \App\Entity\BranchOffice implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".'*'."\0".'slug' => [parent::class, 'slug', null],
        "\0".'*'."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        "\0".parent::class."\0".'exerciseRooms' => [parent::class, 'exerciseRooms', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'place' => [parent::class, 'place', null],
        "\0".parent::class."\0".'public' => [parent::class, 'public', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'exerciseRooms' => [parent::class, 'exerciseRooms', null],
        'id' => [parent::class, 'id', null],
        'isActive' => [parent::class, 'isActive', null],
        'name' => [parent::class, 'name', null],
        'place' => [parent::class, 'place', null],
        'public' => [parent::class, 'public', null],
        'slug' => [parent::class, 'slug', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
