<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class StaffProfile extends \App\Entity\StaffProfile implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".'*'."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        "\0".parent::class."\0".'address' => [parent::class, 'address', null],
        "\0".parent::class."\0".'admissionAt' => [parent::class, 'admissionAt', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'firstname' => [parent::class, 'firstname', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'maternalSurname' => [parent::class, 'maternalSurname', null],
        "\0".parent::class."\0".'paternalSurname' => [parent::class, 'paternalSurname', null],
        "\0".parent::class."\0".'photo' => [parent::class, 'photo', null],
        "\0".parent::class."\0".'photoFile' => [parent::class, 'photoFile', null],
        "\0".parent::class."\0".'staff' => [parent::class, 'staff', null],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null],
        'address' => [parent::class, 'address', null],
        'admissionAt' => [parent::class, 'admissionAt', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'description' => [parent::class, 'description', null],
        'firstname' => [parent::class, 'firstname', null],
        'id' => [parent::class, 'id', null],
        'maternalSurname' => [parent::class, 'maternalSurname', null],
        'paternalSurname' => [parent::class, 'paternalSurname', null],
        'photo' => [parent::class, 'photo', null],
        'photoFile' => [parent::class, 'photoFile', null],
        'staff' => [parent::class, 'staff', null],
        'telephone' => [parent::class, 'telephone', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
