<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Package extends \App\Entity\Package implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".'*'."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        "\0".parent::class."\0".'altText' => [parent::class, 'altText', null],
        "\0".parent::class."\0".'amount' => [parent::class, 'amount', null],
        "\0".parent::class."\0".'daysExpiry' => [parent::class, 'daysExpiry', null],
        "\0".parent::class."\0".'discountInfo' => [parent::class, 'discountInfo', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null],
        "\0".parent::class."\0".'isUnlimited' => [parent::class, 'isUnlimited', null],
        "\0".parent::class."\0".'newUser' => [parent::class, 'newUser', null],
        "\0".parent::class."\0".'public' => [parent::class, 'public', null],
        "\0".parent::class."\0".'specialPrice' => [parent::class, 'specialPrice', null],
        "\0".parent::class."\0".'totalClasses' => [parent::class, 'totalClasses', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        'altText' => [parent::class, 'altText', null],
        'amount' => [parent::class, 'amount', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'daysExpiry' => [parent::class, 'daysExpiry', null],
        'discountInfo' => [parent::class, 'discountInfo', null],
        'id' => [parent::class, 'id', null],
        'isActive' => [parent::class, 'isActive', null],
        'isUnlimited' => [parent::class, 'isUnlimited', null],
        'newUser' => [parent::class, 'newUser', null],
        'public' => [parent::class, 'public', null],
        'specialPrice' => [parent::class, 'specialPrice', null],
        'totalClasses' => [parent::class, 'totalClasses', null],
        'type' => [parent::class, 'type', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
