<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".'*'."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        "\0".parent::class."\0".'birthday' => [parent::class, 'birthday', null],
        "\0".parent::class."\0".'branchOffice' => [parent::class, 'branchOffice', null],
        "\0".parent::class."\0".'conektaId' => [parent::class, 'conektaId', null],
        "\0".parent::class."\0".'confirmationToken' => [parent::class, 'confirmationToken', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'emergencyContactName' => [parent::class, 'emergencyContactName', null],
        "\0".parent::class."\0".'emergencyContactPhone' => [parent::class, 'emergencyContactPhone', null],
        "\0".parent::class."\0".'enabled' => [parent::class, 'enabled', null],
        "\0".parent::class."\0".'freeSession' => [parent::class, 'freeSession', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'lastLogin' => [parent::class, 'lastLogin', null],
        "\0".parent::class."\0".'lastname' => [parent::class, 'lastname', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'passwordRequestedAt' => [parent::class, 'passwordRequestedAt', null],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null],
        "\0".parent::class."\0".'plainPassword' => [parent::class, 'plainPassword', null],
        "\0".parent::class."\0".'reservations' => [parent::class, 'reservations', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'transactions' => [parent::class, 'transactions', null],
        "\0".parent::class."\0".'waitingLists' => [parent::class, 'waitingLists', null],
        'birthday' => [parent::class, 'birthday', null],
        'branchOffice' => [parent::class, 'branchOffice', null],
        'conektaId' => [parent::class, 'conektaId', null],
        'confirmationToken' => [parent::class, 'confirmationToken', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'email' => [parent::class, 'email', null],
        'emergencyContactName' => [parent::class, 'emergencyContactName', null],
        'emergencyContactPhone' => [parent::class, 'emergencyContactPhone', null],
        'enabled' => [parent::class, 'enabled', null],
        'freeSession' => [parent::class, 'freeSession', null],
        'id' => [parent::class, 'id', null],
        'lastLogin' => [parent::class, 'lastLogin', null],
        'lastname' => [parent::class, 'lastname', null],
        'name' => [parent::class, 'name', null],
        'password' => [parent::class, 'password', null],
        'passwordRequestedAt' => [parent::class, 'passwordRequestedAt', null],
        'phone' => [parent::class, 'phone', null],
        'plainPassword' => [parent::class, 'plainPassword', null],
        'reservations' => [parent::class, 'reservations', null],
        'roles' => [parent::class, 'roles', null],
        'transactions' => [parent::class, 'transactions', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
        'waitingLists' => [parent::class, 'waitingLists', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
