<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reservation extends \App\Entity\Reservation implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".'*'."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        "\0".parent::class."\0".'attended' => [parent::class, 'attended', null],
        "\0".parent::class."\0".'cancellationAt' => [parent::class, 'cancellationAt', null],
        "\0".parent::class."\0".'changedAt' => [parent::class, 'changedAt', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isAvailable' => [parent::class, 'isAvailable', null],
        "\0".parent::class."\0".'placeNumber' => [parent::class, 'placeNumber', null],
        "\0".parent::class."\0".'session' => [parent::class, 'session', null],
        "\0".parent::class."\0".'transaction' => [parent::class, 'transaction', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'attended' => [parent::class, 'attended', null],
        'cancellationAt' => [parent::class, 'cancellationAt', null],
        'changedAt' => [parent::class, 'changedAt', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'id' => [parent::class, 'id', null],
        'isAvailable' => [parent::class, 'isAvailable', null],
        'placeNumber' => [parent::class, 'placeNumber', null],
        'session' => [parent::class, 'session', null],
        'transaction' => [parent::class, 'transaction', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
