<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Transaction extends \App\Entity\Transaction implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".'*'."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        "\0".parent::class."\0".'branchOffice' => [parent::class, 'branchOffice', null],
        "\0".parent::class."\0".'cardBrand' => [parent::class, 'cardBrand', null],
        "\0".parent::class."\0".'cardIssuer' => [parent::class, 'cardIssuer', null],
        "\0".parent::class."\0".'cardLast4' => [parent::class, 'cardLast4', null],
        "\0".parent::class."\0".'cardName' => [parent::class, 'cardName', null],
        "\0".parent::class."\0".'cardType' => [parent::class, 'cardType', null],
        "\0".parent::class."\0".'chargeAuthCode' => [parent::class, 'chargeAuthCode', null],
        "\0".parent::class."\0".'chargeId' => [parent::class, 'chargeId', null],
        "\0".parent::class."\0".'chargeMethod' => [parent::class, 'chargeMethod', null],
        "\0".parent::class."\0".'coupon' => [parent::class, 'coupon', null],
        "\0".parent::class."\0".'couponDiscount' => [parent::class, 'couponDiscount', null],
        "\0".parent::class."\0".'discount' => [parent::class, 'discount', null],
        "\0".parent::class."\0".'errorCode' => [parent::class, 'errorCode', null],
        "\0".parent::class."\0".'errorMessage' => [parent::class, 'errorMessage', null],
        "\0".parent::class."\0".'expirationAt' => [parent::class, 'expirationAt', null],
        "\0".parent::class."\0".'expiredAt' => [parent::class, 'expiredAt', null],
        "\0".parent::class."\0".'haveSessionsAvailable' => [parent::class, 'haveSessionsAvailable', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isCompleted' => [parent::class, 'isCompleted', null],
        "\0".parent::class."\0".'isExpired' => [parent::class, 'isExpired', null],
        "\0".parent::class."\0".'package' => [parent::class, 'package', null],
        "\0".parent::class."\0".'packageAmount' => [parent::class, 'packageAmount', null],
        "\0".parent::class."\0".'packageDaysExpiry' => [parent::class, 'packageDaysExpiry', null],
        "\0".parent::class."\0".'packageIsUnlimited' => [parent::class, 'packageIsUnlimited', null],
        "\0".parent::class."\0".'packageSpecialPrice' => [parent::class, 'packageSpecialPrice', null],
        "\0".parent::class."\0".'packageTotalClasses' => [parent::class, 'packageTotalClasses', null],
        "\0".parent::class."\0".'packageType' => [parent::class, 'packageType', null],
        "\0".parent::class."\0".'refundedAt' => [parent::class, 'refundedAt', null],
        "\0".parent::class."\0".'reservations' => [parent::class, 'reservations', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'total' => [parent::class, 'total', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'branchOffice' => [parent::class, 'branchOffice', null],
        'cardBrand' => [parent::class, 'cardBrand', null],
        'cardIssuer' => [parent::class, 'cardIssuer', null],
        'cardLast4' => [parent::class, 'cardLast4', null],
        'cardName' => [parent::class, 'cardName', null],
        'cardType' => [parent::class, 'cardType', null],
        'chargeAuthCode' => [parent::class, 'chargeAuthCode', null],
        'chargeId' => [parent::class, 'chargeId', null],
        'chargeMethod' => [parent::class, 'chargeMethod', null],
        'coupon' => [parent::class, 'coupon', null],
        'couponDiscount' => [parent::class, 'couponDiscount', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'discount' => [parent::class, 'discount', null],
        'errorCode' => [parent::class, 'errorCode', null],
        'errorMessage' => [parent::class, 'errorMessage', null],
        'expirationAt' => [parent::class, 'expirationAt', null],
        'expiredAt' => [parent::class, 'expiredAt', null],
        'haveSessionsAvailable' => [parent::class, 'haveSessionsAvailable', null],
        'id' => [parent::class, 'id', null],
        'isCompleted' => [parent::class, 'isCompleted', null],
        'isExpired' => [parent::class, 'isExpired', null],
        'package' => [parent::class, 'package', null],
        'packageAmount' => [parent::class, 'packageAmount', null],
        'packageDaysExpiry' => [parent::class, 'packageDaysExpiry', null],
        'packageIsUnlimited' => [parent::class, 'packageIsUnlimited', null],
        'packageSpecialPrice' => [parent::class, 'packageSpecialPrice', null],
        'packageTotalClasses' => [parent::class, 'packageTotalClasses', null],
        'packageType' => [parent::class, 'packageType', null],
        'refundedAt' => [parent::class, 'refundedAt', null],
        'reservations' => [parent::class, 'reservations', null],
        'status' => [parent::class, 'status', null],
        'total' => [parent::class, 'total', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
