<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ExerciseRoom extends \App\Entity\ExerciseRoom implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".'*'."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        "\0".parent::class."\0".'branchOffice' => [parent::class, 'branchOffice', null],
        "\0".parent::class."\0".'capacity' => [parent::class, 'capacity', null],
        "\0".parent::class."\0".'discipline' => [parent::class, 'discipline', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'placesNotAvailable' => [parent::class, 'placesNotAvailable', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        'branchOffice' => [parent::class, 'branchOffice', null],
        'capacity' => [parent::class, 'capacity', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'discipline' => [parent::class, 'discipline', null],
        'id' => [parent::class, 'id', null],
        'isActive' => [parent::class, 'isActive', null],
        'name' => [parent::class, 'name', null],
        'placesNotAvailable' => [parent::class, 'placesNotAvailable', null],
        'type' => [parent::class, 'type', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
