<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Session extends \App\Entity\Session implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".'*'."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".'*'."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        "\0".parent::class."\0".'availableCapacity' => [parent::class, 'availableCapacity', null],
        "\0".parent::class."\0".'branchOffice' => [parent::class, 'branchOffice', null],
        "\0".parent::class."\0".'dateStart' => [parent::class, 'dateStart', null],
        "\0".parent::class."\0".'discipline' => [parent::class, 'discipline', null],
        "\0".parent::class."\0".'exerciseRoom' => [parent::class, 'exerciseRoom', null],
        "\0".parent::class."\0".'exerciseRoomCapacity' => [parent::class, 'exerciseRoomCapacity', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'information' => [parent::class, 'information', null],
        "\0".parent::class."\0".'instructor' => [parent::class, 'instructor', null],
        "\0".parent::class."\0".'placesNotAvailable' => [parent::class, 'placesNotAvailable', null],
        "\0".parent::class."\0".'reservations' => [parent::class, 'reservations', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'timeStart' => [parent::class, 'timeStart', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        "\0".parent::class."\0".'waitingList' => [parent::class, 'waitingList', null],
        'availableCapacity' => [parent::class, 'availableCapacity', null],
        'branchOffice' => [parent::class, 'branchOffice', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'dateStart' => [parent::class, 'dateStart', null],
        'discipline' => [parent::class, 'discipline', null],
        'exerciseRoom' => [parent::class, 'exerciseRoom', null],
        'exerciseRoomCapacity' => [parent::class, 'exerciseRoomCapacity', null],
        'id' => [parent::class, 'id', null],
        'information' => [parent::class, 'information', null],
        'instructor' => [parent::class, 'instructor', null],
        'placesNotAvailable' => [parent::class, 'placesNotAvailable', null],
        'reservations' => [parent::class, 'reservations', null],
        'status' => [parent::class, 'status', null],
        'timeStart' => [parent::class, 'timeStart', null],
        'type' => [parent::class, 'type', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
        'waitingList' => [parent::class, 'waitingList', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
